### ISSUE TITLE
깃헙 기록 전 로그 수정

### ISSUE THREAD

**Issue by ohahohah** [pro00er/proMorningReader#1]
[구글독스 - TDD 로그](https://docs.google.com/document/d/18h0KKM_on1dzVaxhWrBj0eFctUpiy5PBKbn23xFl0-U/edit#)

## 서식 수정
- [x] 각 일자별 진도, 진행 날짜 적기  @kimsunoh 
- [x] 타이틀, 인용문 마크다운 적용 - ohaohah
- [x] 목차 작성 - 자동화시키기 @RudiaMoon 

## 자기가 이야기했던 부분 가다듬기
- [x] ksno 파트
- [x] HyeYoung 파트
- [x] ohahohah 파트

**Comment by ohahohah** [comment]
@RudiaMoon  목차작성 관련해서 https://github.com/ekalinin/github-markdown-toc 이거 참고해보셔요

**Comment by ohahohah** [comment]
@RudiaMoon 목차 작성 자동화 되셨으면 해당 내용 공유해주시고, 기존 log 에 목차 적용해주세요

**Comment by kimsunoh** [comment]
이슈 작업 merge 확인되어 issue를 종료합니다
