### ISSUE TITLE
Book_TDD_ch22_20180702 log 작성

### ISSUE THREAD

**Issue by kimsunoh** [pro00er/proMorningReader#43]
**CheckList**
- [x] issue title 형식 지킴? (log_8자리날짜_간략주제 , e.g. log_20180628_python연습문제학습)
- [x] assignees , labels 확인하기 
- [x] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)

**Comment by ohahohah** [comment]
@kimsunoh checkList 다시 확인해주세요~

**Comment by kimsunoh** [comment]
PR merge 완료되어 이슈 종료합니다. 확인 감사드립니다
