### ISSUE TITLE
TDD 실습방법 논의 _180704_현업의 이질성 극복방안

### ISSUE THREAD

**Issue by impactrudia** [pro00er/proMorningReader#47]
## Description
TDD를 현업에서 적용하거나 사용하기 힘든 상황에서 현재 배운것을 어떻게 적용하고 발전시킬지 논의.

- 현업 코드와 비슷한 구조로 하나 만들어서 같이 해보기
  - [ ] 가능할지, 어떤 부분이 문제가 될지, 진행방식에 대해 생각해보기
  - [ ] Agile 팟캐스트, slack에 올려진 아티클들을 읽어보기
  - [ ] Agile 팟캐스트, slack에 올려진 아티클 소감문.

## Reference
- [올바른 코드리뷰 프로세스](https://youtu.be/bQqN4G8tRmY)
- [코드리뷰 라이브 #1](https://youtu.be/ApER4ntDqSQ)
- [페어프로그래밍 첫 도전기](http://blog.dramancompany.com/2015/11/tom%EA%B3%BC-jaden%EC%9D%98-%EC%B2%AB-%ED%8E%98%EC%96%B4-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EB%8F%84%EC%A0%84%EA%B8%B0/)
- [김창준 애자일 키워드 팟캐스트 - 짝프로그래밍](http://www.podbbang.com/ch/14757?e=22408410)
- [김창준 애자일 키워드 팟캐스트 - 테스트주도개발](http://www.podbbang.com/ch/14757?e=22396860)
- [페어 프로그래밍을 넘어서 - Mob programming](http://www.moreagile.net/2014/12/mob-programming.html)
- [Tom과 Jaden의 첫 페어 프로그래밍 도전기](http://blog.dramancompany.com/2015/11/tom%EA%B3%BC-jaden%EC%9D%98-%EC%B2%AB-%ED%8E%98%EC%96%B4-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EB%8F%84%EC%A0%84%EA%B8%B0/)
- [실제로 Pair programming 해보신 분 계신가요???](https://kldp.org/node/111918)
- [취미로 하는 알고리즘 풀이문제](https://www.youtube.com/watch?v=1TVYmKPlNdc&feature=youtu.be)

## CheckList
- [X] issue title 형식 지킴? (log_8자리날짜_간략주제 , e.g. log_20180628_python연습문제학습)
- [X] assignees , labels 확인하기 
- [X] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)
- [X] reference가 있을 경우 해당 정보를 적었는가?
- [ ] PR 하지않고 바로 작업했을 경우 commit hash값을 comment해서 해당 작업내용을 기록

**Comment by ohahohah** [comment]
2019/01/07 부터 각자 TDD 문제 풀기 시작

**Comment by ohahohah** [comment]
오래된 이슈라 종료
