### ISSUE TITLE
TDD 실습 방법 정하기

### ISSUE THREAD

**Issue by ohahohah** [pro00er/proMorningReader#6]
TDD 실습 프로젝트 방법을 정함 - 프로토타입으로 일단 일주일동안 해보기
- [x] 구체적인 방법
- [x] 기간, 일일 분량
- [x] 방법 log에 정리해 남기기

**Comment by kimsunoh** [comment]
book_tdd_Kent_Beck.md 에 20180623 일자 로그에 남겨져 있습니다.
구체화 된다면 따로 md를 분리해서 관리하는건 어떠신가요?

**Comment by ohahohah** [comment]
@kimsunoh meeting_log.md 로 분리되어 있습니다. 해당 내용 확인하시고 기존 PR revert  해주세요
