### ISSUE TITLE
온라인 협업환경 세팅

### ISSUE THREAD

**Issue by ohahohah** [pro00er/proMorningReader#72]
## Description
- 온라인 실습 mob programming을 위한 cloud IDE 세팅
  - AWS Cloud9

**CheckList**
- [x] assignees , labels 확인하기 
- [x] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)

**Comment by kimsunoh** [comment]
해당 이슈는 C9 미사용으로 이슈 종료합니다.
