### ISSUE TITLE
누락로그 확인 및 업무분담

### ISSUE THREAD

**Issue by kimsunoh** [pro00er/proMorningReader#85]
## Description
- 누락된 일자의 로그들을 확인하고, 누락로그를 추가 일자별 담당을 지정한다
- 파일 가독성 높이기위해 각 날짜에 '날짜+ 읽은 장수' 목차로 추가

### 누락로그 업데이트 
- 누락로그 업데이트 스프린트 데이 (2019/01/05)

1. 각각 아래 날짜의 로그 담당하여 업데이트
- part01. 2018/11/11 ~ 2019/01/05 @kimsunoh  
- part02. 2018/07/22 ~ 2018/09/20 @RudiaMoon 
- part03. 2018/07/17 ~ 2018/07/21 @ohahohah 
- part03. 2018/09/21 ~ 2018/11/10 @ohahohah 

2. 안쓰는 브랜치 확인해서 삭제 @kimsunoh 
3. Close 완료된 issue @kimsunoh 
4. on-hold issue 확인해 앞으로 진행계획 작성 @kimsunoh , @ohahohah , @RudiaMoon 
5. 파일 나누기 - 가독성을 위해 파일 나누기 기준 만들고 파일 나누기 @kimsunoh , @ohahohah , @RudiaMoon

## Reference
켄트 벡, TDD

## CheckList
- [x] issue title 형식 지킴? (log_8자리날짜_간략주제 , e.g. log_20180628_python연습문제학습)
- [x] assignees , labels 확인하기 
- [x] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)
- [ ] reference가 있을 경우 해당 정보를 적었는가?

**Comment by ohahohah** [comment]
그동안 쌓인 로그가 많아서, 일단 20181030 로그부터 밀리지 않게 작업 중입니다. @kimsunoh  복귀하시면 그동안의 로그 같이 작업해보아요

**Comment by ohahohah** [comment]
진행하지 않는 이슈임. 종료.
